const PATH = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  SETTING: "/setting",
  SETTING_PROFILE: "/setting/profile",
  SETTING_PHOTO: "/setting/photo",
  SETTING_CHANGE_PASSWORD: "/setting/change-password",
  QUIZZES: "/quizzes",
  RANKING: "/ranking",
  MY_QUIZZES: "/my-quizzes",

  DASHBOARD: "/dashboard",
  CREATE_QUIZ: "/create-quiz",
  CREATE_QUESTION: "/create-question",
  CREATE_TOPIC: "/create-topic",
  UPDATE_QUIZ: "/update-quiz",
  UPDATE_QUESTION: "/update-question",
  HISTORY: "/history",
  PLAY: "/play",
  DASHBOARD_CREATE_QUIZ: "/dashboard/quiz/create",
  DASHBOARD_CREATE_QUESTION: "/dashboard/create/question",
  DASHBOARD_CREATE_TOPIC: "/dashboard/create/topic",
  DASHBOARD_UPDATE_QUIZ: "/dashboard/quiz",
  DASHBOARD_UPDATE_QUESTION: "/dashboard/update/question",
  DASHBOARD_HISTORY: "/dashboard/history",
  DASHBOARD_LIST_QUIZ: "/dashboard/quiz",
  DASHBOARD_LIST_QUESTION: "/dashboard/list/question",
  DASHBOARD_LIST_TOPIC: "/dashboard/list/topic",
  DASHBOARD_LIST_USER: "/dashboard/list/user",
  DASHBOARD_LIST_HISTORY: "/dashboard/list/history",
  DASHBOARD_LIST_RANKING: "/dashboard/list/ranking",
} as const;

export default PATH;
